### ISSUE TITLE
Base Components Frontend

### ISSUE THREAD

**Issue by triumphvalley** [saunah/saunah-frontend#12]
The following base components should be added:
- [x] Button
- [x] IconButton
- [x] Input 
- [x] ~Input validation~ _moved to_ #27
- [x] ~Form (for validation, if needed)~ _moved to_ #27 
- [x] Dropdown
- [x] ~Navbar~ _moved to_ #28
- [x] Alert
- [x] Checkbox (with label)
- [x] ~Dialog~ _moved to_ #28
